sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa {content: "test1", date: "2025-11-29T17:35:51.159Z"}
    activate server
    Note right of browser: The server adds the data and returns status 201 to the browser then the browser refetch the data and rerender the page
    server-->>browser: Status 201
    deactivate server
